### ISSUE TITLE
recurring scheduler does not work right

### ISSUE THREAD

**Issue by peillis** [siwapp/siwapp#103]
This is a test done with heroku scheduler executing `rake siwapp:generate_invoices` every day. The recurring invoice it's supposed to be generated every day, but the fact is that it gets generated every 2 days.

<img width="1257" alt="captura de pantalla 2016-05-14 a las 17 59 06" src="https://cloud.githubusercontent.com/assets/461037/15269462/39d6aabc-19ff-11e6-9941-df082a7cca08.png">

**Comment by ecoslado** [comment]
I was trying the same locally and it works. What do you think that is happening? How does heroku cron work?
