### ISSUE TITLE
Settings forms have no validation nor display errors

### ISSUE THREAD

**Issue by carlosescri** [siwapp/siwapp#108]
not to forget:

days_to_due can't be left blank

**Comment by ecoslado** [comment]
Since Settings model just stores key-value properties, you can't do model-side validation, so I'm looking another way. I found this: https://github.com/cs/active_form. I'm wondering to use it. What about it?

**Comment by peillis** [comment]
+1

**Comment by JoeZ99** [comment]
+1

**Comment by JoeZ99** [comment]
looks like form objects is the way to go
https://www.reinteractive.net/posts/158-form-objects-in-rails

**Comment by JoeZ99** [comment]
@ecoslado , I've started to work on this ticket using "form objects"
https://robots.thoughtbot.com/activemodel-form-objects
you can check some code at the remobe branch, and play around with the /global_settings/new url and input some data.
I think it's the way to go. that would allow us validators and error messages.Pick it up or wait for me.
