### ISSUE TITLE
after adding a payment invoice it's not set as paid

### ISSUE THREAD

**Issue by peillis** [siwapp/siwapp#113]
![captura de pantalla 2016-06-06 a las 11 31 06](https://cloud.githubusercontent.com/assets/461037/15817865/65a80a2c-2bda-11e6-97f6-7cb2498bff11.png)

**Comment by peillis** [comment]
looks like a problem with decimals in BigDecimal types

**Comment by ecoslado** [comment]
I've fixed via 4f863d7..a871ed0
