### ISSUE TITLE
User should be able to set a template to an invoice.

### ISSUE THREAD

**Issue by ecoslado** [siwapp/siwapp#120]
Right now, there's no way to do this. So the idea would be to add a field in the Invoice form to select its template.

**Comment by peillis** [comment]
If an invoice has no template defined (which should happen by default), then the default template is used. If it has any template assigned then used that one.

**Comment by peillis** [comment]
Actually we should assign 2 different templates: for print and for email. 
Recurring invoices too, so generated invoices get the same templates defined in the parent invoice.
