### ISSUE TITLE
Siwapp API

### ISSUE THREAD

**Issue by carlosescri** [siwapp/siwapp#123]
- [x] CRUD invoices
   * `GET http://server/api/v1/invoices`
   * `POST http://server/api/v1/invoices`
   * `PUT http://server/api/v1/invoices/180`
   * `DELETE http://server/api/v1/invoices/180`
 - [x] CRUD payments
   * `GET http://server/api/v1/invocies/180/payments`
   * `POST http://server/api/v1/invoices/180/payments`
   * `PUT http://server/api/v1/payments/34`
   * `DELETE http://server/api/v1/payments.34`
 - [x] CRUD items
   * `GET http://server/api/v1/invoices/180/items`
   * `POST http://server/api/v1/invoices/180/items`
   * `PUT http://server/api/v1/items/34`
   * `DELETE http://server/api/v1/items/34`
 - [x] Filtered invoices listing (per customer, mainly)
   * `GET http://server/api/v1/invoices?q[issue_date_gte]=2016-01-01`
   * `GET http://server/api/v1/invoices?q[with_terms]=pepito+grillo`
   * `GET http://server/api/v1/invoices?q[with_status]=pending`
   * `GET http://server/api/v1/invoices?q[customer_id]=3`
   * `GET http://server/api/v1/customers/1/invoices`
 - [x] Obtain invoice's pdf
   * 
   ````json
{
    "id": 180,
    "series_id": 1,
    "draft": true,
    "...": "...",
    "name": "Demo Company",
    "identification": "D-1234",
    "download_link": "http://localhost:3000/invoices/template/1/invoice/180.pdf",
    "..." : "..."
   ````
 - [x] Auth mechanism

**Comment by facine** [comment]
I think we also need:
- [ ] List, create, update series
- [ ] List, create, update taxes
- [ ] Create, update and search customers

**Comment by JoeZ99** [comment]
of  course, the beginning list was just to get started

**Comment by JoeZ99** [comment]
@carlosescri , I'm starting to toy around with the API.
The first thing is how to properly represent invoices as json.

  - I've included nested a simplified version items, payments and customer, 
  - As for the series, instead of incluidng it as  a complete json, I've only put the series_id, doesn't. for the series value and all that, I've included an informative field `series_number`
  - Haven't included `status` as the integer it is, seemed to binded to internal management of our databases, and maybe changeable. I've included the informative "stringified" version of status
  - `draft` seems like a valid boolean.
  - `paid` is merely informative, and its info it's included in the "stringified" version of statys
  - `days_to_due`, I'm not very sure

Anyway, I'm just doing it as it seems fit, with no knowledge of "best practiques" or anything, I would appreciate your input on this.


````json
{
    "id": 2,
    "series_id": 3,
    "draft": false,
    "sent_by_email": false,
    "name": "Warehousing",
    "identification": "C-1234",
    "email": "info@warehousing.com",
    "invoicing_address": null,
    "shipping_address": null,
    "contact_person": null,
    "terms": null,
    "notes": null,
    "base_amount": "3086.57",
    "discount_amount": "0.0",
    "net_amount": "3086.57",
    "gross_amount": "3532.0539",
    "paid_amount": "0.0",
    "tax_amount": "445.4839",
    "issue_date": "2016-05-11",
    "due_date": "2016-06-11",
    "days_to_due": null,
    "created_at": "2016-05-13T03:36:04.000Z",
    "updated_at": "2016-05-13T03:36:04.000Z",
    "series_number": "SSC-10",
    "status": "overdue",
    "customer": {
        "id": 3,
        "name": "Warehousing",
        "identification": "C-1234",
        "email": "info@warehousing.com"
    },
    "items": [
        {
            "id": 9,
            "description": "Personal Drone",
            "unitary_cost": "95.74",
            "quantity": "3.0",
            "discount": "0.0"
        },
        {
            "id": 10,
            "description": "Paper",
            "unitary_cost": "27.35",
            "quantity": "10.0",
            "discount": "0.0"
        },
        {
            "id": 11,
            "description": "Drowning kit",
            "unitary_cost": "77.96",
            "quantity": "10.0",
            "discount": "0.0"
        },
        {
            "id": 12,
            "description": "Weird shoe lazes",
            "unitary_cost": "97.2",
            "quantity": "2.0",
            "discount": "0.0"
        },
        {
            "id": 13,
            "description": "Personal Drone",
            "unitary_cost": "22.38",
            "quantity": "1.0",
            "discount": "0.0"
        },
        {
            "id": 14,
            "description": "Paper",
            "unitary_cost": "81.37",
            "quantity": "1.0",
            "discount": "0.0"
        },
        {
            "id": 15,
            "description": "Paper",
            "unitary_cost": "47.68",
            "quantity": "10.0",
            "discount": "0.0"
        },
        {
            "id": 16,
            "description": "Weird shoe lazes",
            "unitary_cost": "20.66",
            "quantity": "10.0",
            "discount": "0.0"
        },
        {
            "id": 17,
            "description": "Fishing kit",
            "unitary_cost": "76.47",
            "quantity": "10.0",
            "discount": "0.0"
        }
    ],
    "payments": [
        {
            "id": 2,
            "date": "2016-05-12",
            "amount": "0.0",
            "notes": "Paid by american express."
        }
    ]
}
````

**Comment by JoeZ99** [comment]
@carlosescri , I've just merged this. I thinks it's more or less complete. I'm going to do the tests now. I've had to redo everything when I realized API should be in a separate namespace.

Anyway, the auth token is generated in siwapp web, on the "API Token" section of "my account", I'm afraid I can't get it to look nice. Would you please have a look?

**Comment by JoeZ99** [comment]
some features missing:
  - [ ] Pagination links
  - [ ]  On listings, iinfo about the total num of results

**Comment by JoeZ99** [comment]
all right. pagination and total info is on headers now. Body is only about the data
