### ISSUE TITLE
API: allow creation of invoices with payments

### ISSUE THREAD

**Issue by ecoslado** [siwapp/siwapp#132]
I send a post with  body:
```JSON
{"series_id":2,"draft":false,"sent_by_email":false,"name":"Demo Company","identification":"D-1234","email":"info@democompany.com","invoicing_address":null,"shipping_address":null,"contact_person":null,"terms":null,"notes":null,"base_amount":"1260.61","discount_amount":"91.11","net_amount":"1169.5","gross_amount":"1383.51","paid_amount":"0.0","tax_amount":"214.0113","issue_date":"2016-08-23","due_date":"2016-09-23","days_to_due":null,"created_at":"2016-08-24T07:31:43.000Z","updated_at":"2016-08-24T07:31:43.000Z","url":"http://localhost:3000/api/v1/invoices/10","status":"paid","customer":"http://localhost:3000/api/v1/customers/4","items":[{"description": "Lorem ipsum", "quantity": 2, "cost": 3, "total": 6, "taxes": []}]
}
```
The response I get:
```JSON
{
  "id": 16,
  "series_id": 2,
  "draft": false,
  "sent_by_email": false,
  "name": "Demo Company",
  "identification": "D-1234",
  "email": "info@democompany.com",
  "invoicing_address": null,
  "shipping_address": null,
  "contact_person": null,
  "terms": null,
  "notes": null,
  "base_amount": "0.0",
  "discount_amount": "0.0",
  "net_amount": "0.0",
  "gross_amount": "0.0",
  "paid_amount": "0.0",
  "tax_amount": "0.0",
  "issue_date": "2016-08-23",
  "due_date": "2016-09-23",
  "days_to_due": null,
  "created_at": "2016-08-24T08:37:54.099Z",
  "updated_at": "2016-08-24T08:37:54.118Z",
  "url": "http://localhost:3000/api/v1/invoices/16",
  "series_number": "SSB-13",
  "status": "paid",
  "download_link": "http://localhost:3000/api/v1/invoices/template/1/invoice/16.pdf",
  "customer": {
    "id": 4,
    "identification": "D-1234",
    "url": "http://localhost:3000/api/v1/customers/4"
  },
  "items": [],
  "payments": []
}
```
And the invoice has no items in Siwapp GUI.

**Comment by JoeZ99** [comment]
check https://github.com/siwapp/siwapp/#create you need to use "items_attributes" instead of "items".

**Comment by ecoslado** [comment]
Yep, but I've tried with items_attributes too (I was trying multiple ways indeed), with the same result. Could you check if it's working for you and send me a real example please?

**Comment by JoeZ99** [comment]
willdo

**Comment by JoeZ99** [comment]
@ecoslado you have to send invoice attributes within the "invoice" key. instead of

```json
{
  "series_id":2,
  "draft":false,
  "sent_by_email":false,
  "name":"Demo Company",
  "identification":"D-1234",
  "email":"info@democompany.com",
  "invoicing_address":null,
  "shipping_address":null,
  "contact_person":null,
  "terms":null,
  "notes":null,
  "base_amount":"1260.61",
  "discount_amount":"91.11",
  "net_amount":"1169.5",
  "gross_amount":"1383.51",
  "paid_amount":"0.0",
  "tax_amount":"214.0113",
  "issue_date":"2016-08-23",
  "due_date":"2016-09-23",
  "days_to_due":null,
  "created_at":"2016-08-24T07:31:43.000Z",
  "updated_at":"2016-08-24T07:31:43.000Z",
  "url":"http://localhost:3000/api/v1/invoices/10",
  "status":"paid",
  "customer":"http://localhost:3000/api/v1/customers/4",
  "items":[
    {"description": "Lorem ipsum", "quantity": 2, "cost": 3, "total": 6, "taxes": []}
  ]
}
```


do


```json
{
  "invoice": {
    "series_id":2,
    "draft":false,
    "sent_by_email":false,
    "name":"Demo Company",
    "identification":"D-1234",
    "email":"info@democompany.com",
    "invoicing_address":null,
    "shipping_address":null,
    "contact_person":null,
    "terms":null,
    "notes":null,
    "base_amount":"1260.61",
    "discount_amount":"91.11",
    "net_amount":"1169.5",
    "gross_amount":"1383.51",
    "paid_amount":"0.0",
    "tax_amount":"214.0113",
    "issue_date":"2016-08-23",
    "due_date":"2016-09-23",
    "days_to_due":null,
    "created_at":"2016-08-24T07:31:43.000Z",
    "updated_at":"2016-08-24T07:31:43.000Z",
    "url":"http://localhost:3000/api/v1/invoices/10",
    "status":"paid",
    "customer":"http://localhost:3000/api/v1/customers/4",
    "items":[
      {"description": "Lorem ipsum", "quantity": 2, "cost": 3, "total": 6, "taxes": []}
    ]
  }
}
```

by the way, instead of "customer" use "customer_id" (or nothing) and instead if "taxes", use "tax_ids"

I think it's all in the doc, but please tell me.

**Comment by JoeZ99** [comment]
Sorry I forgot. In addition to my last comment, don't use the `"items"` key but `"items_attributes"`

**Comment by ecoslado** [comment]
Items are storing OK, as you said the whole thing is in the docs. Just another thing. I'm trying to store:

```python
{'invoice': {'issue_date': '2016-09-01', 
'created_at': '2016-09-01', 
'terms_and_conditions': None, 
'series_id': 2, 
'payments_attributes': [{'date': '2016-09-01', 'notes': 'Payment', 'amount': 27.78}], 'identification': 'ESWEYLANDYUTANI', 
'items_attributes': [{'unitary_cost': 48.92, 'tax_ids': [1], 'total': 59.19, 'description': 'Size M', 'quantity': 1}, {'unitary_cost': 8.99, 'tax_ids': [1], 'total': 10.88, 'description': 'Mobile Version', 'quantity': 1}, {'unitary_cost': -28.96, 'tax_ids': [1], 'total': -35.04, 'description': 'Credit for remaining Size S', 'quantity': 1}, {'unitary_cost': -5.99, 'tax_ids': [1], 'total': -7.25, 'description': 'Credit for remaining Mobile Version', 'quantity': 1}], 
'invoicing_address': '1234 1234 Madrid Madrid - 28002, ES'}}
```

And I get:

```python 
{u'payments.invoice_id': [u"can't be blank", u'is not a number']}
```

Notice I'm trying to index this document with payments_attributes but three birds aren't singing this time. Any ideas?

**Comment by JoeZ99** [comment]
well, I may misunderstood how it was supposed to work. I assumed an invoice shouldn't be created with payments already, so payments must be added using the payments create entrypoint. I guess I thought you issue an invoice before start getting payments. If you think that's a plausible use case, we could enable creating nvoices with payments in the same request. Right now you need to create the invoice first and then start adding payments.

**Comment by JoeZ99** [comment]
well, I may misunderstood how it was supposed to work. I assumed an invoice shouldn't be created with payments already, so payments must be added using the payments create entrypoint. I guess I thought you issue an invoice before start getting payments. If you think that's a plausible use case, we could enable creating nvoices with payments in the same request. Right now you need to create the invoice first and then start adding payments.

By the way, whose guy is you avatar picture from???

**Comment by JoeZ99** [comment]
well, I may misunderstood how it was supposed to work. I assumed an invoice shouldn't be created with payments already, so payments must be added using the payments create entrypoint. I guess I thought you issue an invoice before start getting payments. If you think that's a plausible use case, we could enable creating nvoices with payments in the same request. Right now you need to create the invoice first and then start adding payments.

By the way, whose guy is you avatar picture from???

**Comment by peillis** [comment]
I guess payments could be added both ways.

**Comment by JoeZ99** [comment]
@peillis, do you think we should enforce the `date` field when adding payments? looks like a pretty essential field to me, but I'm not that versed in the world of invoicing. 
I guess we shouldn't let a payment to be added without a date. In that case we ca:
  - don't accept payments without date
  - automatically stamp today's date if a date is not supplied.

**Comment by JoeZ99** [comment]
Ok, now I see we automatically set date for today when adding a payment through the webpage, I guess the translation to that to the API world would be "use today if none given"
