### ISSUE TITLE
'terms' and 'notes' are fields that doesn't belong to customer. remove them from customer's form

### ISSUE THREAD

**Issue by JoeZ99** [siwapp/siwapp#155]
`temrs` and `notes` text areas, are included in `views/customers/_form_fields.html`, but they only belong to `common`, and the customers edit page throws 500 when trying to edit customers.

It wasn't noticed before because there were no `notes` text area and the `terms` text area had the `value: @global_settings` option -which was wrong too, but didn't throw any errors- that masked it.

Now it just has a quick `unless` condition to prevent the 500, but they really should be located out of that partial. And be somewhere in the `invoice` and `recurring_invoice` editing form

**Comment by peillis** [comment]
I don't see any terms or notes fields on the customer's form
