### ISSUE TITLE
remove all the json views we don't use

### ISSUE THREAD

**Issue by peillis** [siwapp/siwapp#166]
I think most of the json views are now under the api folder, only the autocompletes and calculations should be used.

**Comment by ecoslado** [comment]
Since we are using ActiveModel Serializers for API maybe we can dispense with jbuilder

**Comment by peillis** [comment]
@ecoslado is this done?

**Comment by ecoslado** [comment]
I removed everything from API, but there are some views in the GUI part that are using jbuilder (like amounts.json).  The ideal should be replace this part to do everything with Serializers.
