### ISSUE TITLE
website outdated

### ISSUE THREAD

**Issue by cwittmer** [siwapp/siwapp#200]
Hi
the website is outdated and is telling about **siwapp-sf1** (0.4.2beta) as current version. But this is mentioned on github as **_NO LONGER MAINTAINED_** anymore. Same for **siwapp-sf2** and for Installation Guide.
Will someone please be so kind and update the information ?

And please advise:
What is the correct current version to use ?
How to update to current version ?

Thank you

**Comment by peillis** [comment]
Hi, strictly speaking the version on the web is the current, because the others are under development, but as far as I know the sf3 should be working, and the RoR version too but it's up to you which one install.
