### ISSUE TITLE
Invoces List Page: weird behavior when paging

### ISSUE THREAD

**Issue by ecoslado** [siwapp/siwapp#209]
Sometimes, when you scroll down you can see some repeated invoices. I'm not really sure about this but I think this behavior can be produced by the next use case:
- You are viewing invoice list.
- A new invoice is created via API (or by another user).
- You retrieve next page and the latest invoices in first page have been moved to the next page.

Thinking about this, I don't know if it is a corner case, but I've experienced this a few times the last days.

**Comment by peillis** [comment]
well I guess the pagination gets confused when having more invoices than initially... I don't know, maybe there is a solution

**Comment by ecoslado** [comment]
Ok, I close it
