### ISSUE TITLE
Items are not removed from Invoices.

### ISSUE THREAD

**Issue by mdogo** [siwapp/siwapp#266]
When an user tries to remove an item from a invoice in siwapp, and he hit save, everything seems to be working fine but the item remains.

**Comment by peillis** [comment]
@carlosescri how come this is not covered by tests?

**Comment by carlosescri** [comment]
I don't know why but I forgot to complete the test. I just left it commented in `spec/features/invoices/update_spec.rb`.

**Comment by peillis** [comment]
fix this ASAP please

**Comment by carlosescri** [comment]
Ok, this will be my good deed of the week...
