### ISSUE TITLE
API: returns 500 when searching by meta[account_code]=e7aa2daca50ce4f729a98cd1866123

### ISSUE THREAD

**Issue by ecoslado** [siwapp/siwapp#275]
And just for this account_code. I tried to reproduce it locally and I couldn't. I tried to search another account_code and I found it. I tried to search this account_code from the GUI and it worked.

https://siwapp-doofinder.herokuapp.com/api/v1/invoices?meta[account_code]=e7aa2daca50ce4f729a98cd1866123

**Comment by peillis** [comment]
I've checked this and works
