### ISSUE TITLE
API Search Between Date's Isn't Working

### ISSUE THREAD

**Issue by chavenor** [siwapp/siwapp#282]
It's giving me an invoice that was created on 2017-4-17. 
Any reason why? 

```python
data = requests.get(url=url_base+"invoices?q[issue_date_lte]=2017-04-10&q[issue_date_gte]=2017-04-09", headers=headers, timeout=api_timeout)
pprint(data.json())
```

**Comment by peillis** [comment]
Actually it's documentation which is wrong. You should use the parameters `q[issue_date_lteq]` and `q[issue_date_gteq]`
I'm gonna fix docs.

**Comment by chavenor** [comment]
Thanks!
