### ISSUE TITLE
Unable to build reoccurring invoices when set in the past?

### ISSUE THREAD

**Issue by chavenor** [siwapp/siwapp#293]
I just added a bunch of invoices that were set to the first of this month but when I try to build them the build button is not highlighted and disabled? 

Any clue as to what is going on?

**Comment by peillis** [comment]
Hi, can you give us more info how to reproduce that? Maybe you could make a test in the demo site: https://siwapp-demo.herokuapp.com

**Comment by chavenor** [comment]
What is the login and password?

**Comment by peillis** [comment]
User: demo@example.com / Password: secret

**Comment by chavenor** [comment]
I was able to create an air with a series of a larger number. 

Not sure if it's related. Check the logs on your end. 

I change series A- two 11111111

**Comment by peillis** [comment]
So did it work?

**Comment by chavenor** [comment]
Looks like it did
