### ISSUE TITLE
How do you generate the pending reoccurring invoices by API?

### ISSUE THREAD

**Issue by chavenor** [siwapp/siwapp#300]
How do you generate the pending reoccurring invoices by API?

**Comment by peillis** [comment]
Recurring invoices are generated in the server by a script, there is no need to use the API for that.

**Comment by chavenor** [comment]
@peillis I'm more confused now because I've had to manually create all my re-occurring invoices.  They have never automatically been created for me.    Am I missing a setting?

**Comment by peillis** [comment]
In the README is explained how to do it. It's the `rake siwapp:generate_invoices` command. You can configure that on Heroku as explained in the readme, or configure a crontab which executes every day.
