### ISSUE TITLE
Installation, internal server error

### ISSUE THREAD

**Issue by yeu** [siwapp/siwapp#37]
Hello,

I can't install siwapp either in localhost or remote server.

In remote case the error is the following:

*Internal Server Error*
*The server encountered an internal error or misconfiguration and was unable to complete your request.*
*Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.*

Can I use file .zip from github or another release to fix this problem? The siwapp official release is dated 2012 (version 0_4_1 beta).

I followed all the installation settings yet (write permissions, root and web directory , etc. ).

Thank you!

**Comment by yeu** [comment]
Update, error log is:

Option FollowSymLinks not allowed here

**Comment by carlosescri** [comment]
Hi Yeu,

This repository is for the new Ruby version. You can find solutions to common problems in the groups: <http://www.siwapp.org/es/community.html>.
