### ISSUE TITLE
adding payments autocomplete

### ISSUE THREAD

**Issue by peillis** [siwapp/siwapp#39]
when adding a payment it should autocomplete: date with actual date, amount with the remain to be paid.

**Comment by JoeZ99** [comment]
We can do this perfectly well using default values. Every time a payment is added, it shows up with the date field set as today and the amount field set as what's left.

It's simpler than setting an "autocomplete" feature which doesn't make many sense here, unless we want to identify payments by the "notes" field. Even so, if that's the case, then the amount field should be filled with the amount of whatever previous payment is selected based on its "notes" fields.

**Comment by peillis** [comment]
that's right. By autocomplete I didn't mean the usual meaning, but just that the field is already filled.
