### ISSUE TITLE
there must be not signup page

### ISSUE THREAD

**Issue by peillis** [siwapp/siwapp#40]
just make a rake task to add users

**Comment by carlosescri** [comment]
I think that a superuser should be created on install and that user should be able to add more users from the settings page (if we want to make it easy to use).

**Comment by peillis** [comment]
+1

**Comment by carlosescri** [comment]
But rake tasks are useful as an extra:

- To add a user
- To change a user password

Also, current user should be able to change her password from the admin.

**Comment by ecoslado** [comment]
I replaced the signup page and put an update user page in its place.
