### ISSUE TITLE
Fix properties table structure: use the same in all places

### ISSUE THREAD

**Issue by carlosescri** [siwapp/siwapp#44]
In `lib/tasks/migration.rake`:

```ruby
client.query("ALTER TABLE property DROP PRIMARY KEY")
client.query("ALTER TABLE property CHANGE `keey` `key` VARCHAR(255) NOT NULL")
client.query("ALTER TABLE property ADD id INT NOT NULL PRIMARY KEY AUTO_INCREMENT")
client.query("ALTER TABLE property CHANGE value value TEXT")
```

(we are adding an `id` as PK).

In `schema.rb`:

```ruby
create_table "properties", primary_key: "keey", force: :cascade do |t|
  t.text "value", limit: 65535
end
```

(`keey` is the PK).

**Comment by peillis** [comment]
it was ok but @JoeZ99 changed it, just look for the previous version. It should be right there.

**Comment by JoeZ99** [comment]
I reverted that change the very same day , didn't make any modification to schema.rb at the end.  `schema.rb` and `migration.rake` haven't been modified by me.

**Comment by carlosescri** [comment]
Yep, I've dropped my db and created again and everything is fine now.
