### ISSUE TITLE
Workaround for troublesome import

### ISSUE THREAD

**Issue by dev-brother** [siwapp/siwapp#45]
Hi Guys

Siwapp rocks in simplicity. Thanks.

One issue which is a bain is exporting and importing database files. Have had to do this on more than one occasion, migrating to a new server over the years, and import always fails irrespective of Os.

Isn't there an easier way to migrate data?

**Comment by peillis** [comment]
Hi, you should post this into the users group. This is for development of the ruby version of siwapp.
Thanks!
