### ISSUE TITLE
on listing series there must be a way to select the default one

### ISSUE THREAD

**Issue by peillis** [siwapp/siwapp#53]
And when making a new invoice that serie should be selected by default.

**Comment by JoeZ99** [comment]
two choices here, I guess:

   - add a "default" boolean field to the model
   - add a custom setting. I'd rather choose this last one.

**Comment by peillis** [comment]
Ok about a custom setting, but then do the same with taxes

**Comment by ecoslado** [comment]
@JoeZ99, on this, @serguitus chose the "default" boolean field and I think it's easier to implement and maintain than a property per default setting we need. The only problem could be with this is more than one default element, but this can be solved by unchecking the rest of the elements when one is set. So I think I'll continue this strategy  in @serguitus' branch.
