### ISSUE TITLE
periodic background generation of recurring invoices

### ISSUE THREAD

**Issue by JoeZ99** [siwapp/siwapp#57]
@peillis
to put this on writing

  - the idea is that every day all pending recurring invoices are generated.
  - if pending invoices are generated once a day, there is an out-of-sync period, maybe we could also add a "sync pending invoices" or something, so the user can have up-to-date inovices

**Comment by peillis** [comment]
I don't get the second point. Why is there an out-of-sync period?

**Comment by JoeZ99** [comment]
@peillis

lo del "out of sync" es poco importante. Si las pending se generan todos los días a las 10 de la mañana, las pending que deberían haber sido generadas entre las 10 de la mañana de ese día y las 10 de la mañana del día siguiente no están generadas y por tanto "out of sync"

con respecto al scheduling ,   estas son más o menos nuestras opciones:

  - creo que los candidatos a proceso asíncrono serían
    * sucker punch: es prácticamente "lo mínimo" en proceso asíncrono. No necesita un proceso worker aparte. pero tampoco tiene una api para "manejar la cola" (en plan de saber los trabajos que estén en cola, los trabajos pendientes, vaciar la cola, etc ) https://github.com/brandonhilkert/sucker_punch
    * delayed job: es la siguiente en sencillez. esta ya necesita una tarea rake aparte, es decir un proceso rails aparte, No tiene una API de queue management (casi ninguno la tiene), pero como trabaja basado en ActiveRecord, se pueden usar los registros de la base de datos en caso de necesitar algo de ese estilo (cancelar trabajos o cosas asi)
https://github.com/collectiveidea/delayed_job/tree/v4.1.1
    *  resque: es una especie de "delayed_job en serio" , que usa redis en el background y me parece un poco overkill. resque tiene de todo pero ellos mismos recomiendan no meterse en ese berenjenal si con delayed_job se puede resolver.
https://github.com/resque/resque/tree/1-x-stable
    * sidekiq es una opción de pago con una versión open source. es muy "high-end", como resque, pero mejor y mas bonito.
http://sidekiq.org/
 


  - en general lo de la tarea "periodica" no es tan obvio como parecía. Ninguna de las opciones tiene scheduling . En este sentido hay tres opciones:
    * extensiones:
      - delayed_job_recurring: la más sencilla (again) pero el comando que se usa para "schedulear" las tareas, si se ejecuta doblemente, las "schedulea" doblemente, así que tendríamos que poner una serie de prevenciones.
      - resque-scheduler . bastante atómica pero, de nuevo, overkill
      - sidetiq : idem
    * proceso tipo "cron" separado:
       - crono: supersencillo es como un crontab para ruby
       - clockwork algo mas sofisticado
       - etc...
    * usar el scheduler de heroku. heroku tiene un "scheduler" con una interfaz web que se puede usar para programar el cumplimiento de ciertas tareas periodicamente


podemos o bien usar un cron y el sucker punch, y tendriamos que inventar algo para tener una idea de si las tareas se acaban o no (algun tipo de locking)

podemos tener un delayed_job con la extension delayed_job_recurring e inventar algo para que el comando Job.schedule! (que es el que coloca os trabajos para ejecutarse según cierto horario) no se ejecute múltiples veces. para el control de queue, usamos activerecord.

podemos tener un delayed_job con un proceso cron aparte. ahí no hay que inventar nada.

**Comment by peillis** [comment]
De todas formas no hay por qué planteárselo como tasks, porque bastaría un cron o similar que chequee por cada recurring si tiene o no que generar nuevas facturas y cuantas y con qué fechas. Ese cron debería poder correr todas las veces que haga falta sin importar eso.

**Comment by carlosescri** [comment]
De hecho se puede hacer en cliente, enviando órdenes al servidor mientras el usuario utiliza la app. Tengo algunas ideas sobre esto.

C.

**Comment by peillis** [comment]
pero hay que hacer que las facturas se generen aunque el usuario no entre en la aplicación, por lo que no creo que tenga mucho sentido eso.

**Comment by JoeZ99** [comment]
aun sin plantearselo como tasks, si lo queremos hacer con regularidad, necesitamos un proceso extra o dos.

  -  Uno para el cron y otro para la generacion de las nuevas facturas. 
  -  O 1 para la generacion de las facturas que sea capaz de hace schedulling (usando el delayed job con la extension apropiada). O 
   - 1 para el cron que además se encarge de generar las facturas  (no me gusta)

efectivamente, la generacion de facturas es idempotente, así que se puede ejecutar todas las veces que haga falta.

@carlosescri , ¿cuáles son tus ideas acerca de generarlo "en cliente"? a mí lo único que no me gusta de eso es que sii se generan "cuando el cliente hace login" y cosas así, va a provocar que los issue_date de esas facturas estén "clustereados". es decir, si unas facturas recurrentes deberían generarse en los días 10,20 y 30 del mes, y no hay un cron sino que en el momento en que se hace login se generan todas las pendientes, si sólo se hace login el 30 ahí se generarían todas con el mismo issue date las facturas del 10,20 y 30 . Eso no es tan grave pero suena "messy".

**Comment by peillis** [comment]
¿qué problema tiene el cron que genere las facturas?

**Comment by JoeZ99** [comment]
pues que el cron deberia ser un proceso "ligero" y que si lo comprometemos a hacer procesos largos, puede que "se salte" alguna entrada (porque esta entretenido en alguna generacion)

pero realmente de momento no deberiamos preocuparnos por eso. la generacion de pending no es tan pesada, sobre todo si se hace "on schedule".

**Comment by carlosescri** [comment]
Nada, lo de hacerlo en cliente solamente tiene sentido para los que no tienen cron, pero tampoco puedes programar milagros, ¿no?  El que quiera facturas generadas automáticamente que se lo curre. 

C.
