### ISSUE TITLE
DRY: use rails-settings-cached.

### ISSUE THREAD

**Issue by JoeZ99** [siwapp/siwapp#74]
It's kind of the same princile: property-value tables for specific settings. Also comes with caching mecahnism.

https://github.com/huacnlee/rails-settings-cached

**Comment by JoeZ99** [comment]
why are you so mean to me???

**Comment by JoeZ99** [comment]
so very mean ....

**Comment by ecoslado** [comment]
what do you "mean"?

**Comment by JoeZ99** [comment]
You just close the issue with no respect for the old guys . "mean" means "bad with somebdy". Don't you think is worth it to use this gem? I was thinking it won't affect the code and we'll get rid of some tables...

**Comment by ecoslado** [comment]
I've closed it, cause I did it. I installed the gem and it's being used.

2016-03-17 15:04 GMT+01:00 JoeZ99 <notifications@github.com>:

> You just close the issue with no respect for the old guys . "mean" means
> "bad with somebdy". Don't you think is worth it to use this gem? I was
> thinking it won't affect the code and we'll get rid of some tables...
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/siwapp/siwapp/issues/74#issuecomment-197892338>
>



-- 
*Kike Coslado*
Software Engineer

*DOOFINDER*
Lopez de Hoyos 135, 4A
28002 - Madrid
http://www.doofinder.com

**Comment by JoeZ99** [comment]
ah, ok [flushing] I'm just not used to my proposals being accepted with no arguments. Sorry. [more flushing]
