### ISSUE TITLE
use gon to pass variables from the controller to js ???

### ISSUE THREAD

**Issue by JoeZ99** [siwapp/siwapp#85]
https://github.com/gazay/gon

in a nutshell:
define ruby variables in controller and access them through the "gon" javascript object.

I'm not very keen , actually, but it may come handy for passing the rounding precision to javascript (which depends on the currency used).

**Comment by JoeZ99** [comment]
this guy, tals about gon
https://launchschool.com/blog/rails-asset-pipeline-best-practices

in his opinion, it's not that bad.

**Comment by ecoslado** [comment]
Fix #78 properly by using gon objects.

**Comment by JoeZ99** [comment]
I mean, if you decide Gon is the way to go.

**Comment by ecoslado** [comment]
We'll see, otherwise I would reopen #78.

**Comment by JoeZ99** [comment]
it's your responsability

**Comment by ecoslado** [comment]
I've included the gon gem and render a gon object in layout/application.html. Seems to be good idea, maybe we have to get a convention to give names to this variables.

I'm trying right now do #78 by passing a gon object but the thing is that you are iterating between items when you calculate this total and I don't know where could I inject this calculation. 

Any ideas?

**Comment by JoeZ99** [comment]
I don't quite understand you, I'm afraid. But if you think about it, these amounts are not numbers, are currencies, so there is no such thing as a "payment" or a "unitary price" which can have any number of decimals, they all are money so all the quantities are restricted to the currency settings decimals. In fact I think we should start considering using the money-gems, which I was against at the begining, se we can start handling money properly. That is: the money amount is always saved as an integer representing the minimum fraction of the currency. I.e.: 13.62 € is saved as 1362 cents. Because money is always an integer amount... It shouldn't be needed to "round" anything from this perspective (well, only when dividing an amount in parts, but that's not what an invoicing application does).

**Comment by ecoslado** [comment]
What I can't see is where I store the pre-calculated amounts to be displayed. I recognise I'm a little lost in this data flow. How would you calculate and use this data?

**Comment by JoeZ99** [comment]
enrique, ahora el perdido soy yo, me puedes poner un ejemplo con codigo??? el issue es simplemente que en los input que se autorellenan con el recalculo del total para el item especifico (cuando cambias cantidad , precio unitario, descuento o impuestos), ese total se muestre redondeado acorde el currency. 

Lo que te decía antes era que todo esto sospecho que se nos va a quedar obsoleto cuando empecemos a guardar -y admitir inputs- de la currency como se debe, es decirla cantidad exacta de unidades minumas de la moneda en cuestión, pero bueno ya llegaremos a eso. de momento basta con que las cifras decimales sean las que corresponden a la moneda en cuestion

**Comment by ecoslado** [comment]
el problema que tengo es que no sé cómo inyectar los totales precalculados en el código javascript. Ahora mismo se trata de manera aislada la actualización de un item y se hace del lado del cliente. 
```coffeescript
# Find forms that behave like an invoice:
  $('form[data-role="invoice"]').each ->
    form = $(this)
    controller_name = form.data('controller')  # REQUIRED!!!

    autosize form.find('textarea')

    # Find sections that change the amounts of the invoice-like form
    form.find('[data-changes="amount"]')
      # When an item changes, update form amounts
      .on 'change input', '.js-item', (e) ->
        item = $(e.target)
        if item.prop 'tagName' == 'TEXTAREA'
          return
        # Set the base amount of the item = quantity * unitary_cost
        # Attention: discounts and taxes are not calculated here!!
        # those are calculated only in the totals.
        item_row = item.parents('.js-item')
        base_amount = Math.round(item_row.find('.quantity').val()*item_row.find('.unitary-cost').val()*10**2)/10**2
        item_row.find('[data-role="base-amount"]').val(base_amount)
        item_row.find('.js-base-amount').html(base_amount)
```
El InvoiceController está ejecutando el método edit en ese momento. Cómo inyecto las cantidades desde el controller.

**Comment by JoeZ99** [comment]
creo que no tienes que inyectar ninguna cantidad desde el controller. todo lo que el javascript necesita para los calculos, esta presente en el formulario de la pagina web, son los valores de los campos "quantity" , "amount" y "unitary_cost"

cada vez que se cambia "amount" "quantity" y "unitary_cost", se recalcula "base_amount" del lado del cliente con los valores de los campos del formulario, y se hace una peticion al controller para que recalcule los amounts totales, pero esos amounts totales salen en otra seccion de la pagina.

**Comment by ecoslado** [comment]
entonces qué haríamos aquí con el objecto gon

**Comment by JoeZ99** [comment]
el objeto gon en este caso es simplemente para que el javascript sepa
cuantos decimales tiene que redondear, porque eso depende del currency

On Wed, Apr 27, 2016 at 10:49 AM, Enrique Coslado Santibáñez <
notifications@github.com> wrote:

> entonces qué haríamos aquí con el objecto gon
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/siwapp/siwapp/issues/85#issuecomment-215108112>
>



-- 
uh, oh <http://www.youtube.com/watch?v=GMD_T7ICL0o>.

<http://www.defectivebydesign.org/no-drm-in-html5>

**Comment by peillis** [comment]
esta mañana hablábamos que lo mejor con esos cálculos sería hacerlos siempre en ruby, y que el javascript no tenga que calcular nada.

**Comment by JoeZ99** [comment]
de hecho, cada vez que se modifica un valor en uno de esos campos, se llama al "set_amounts" del controller (para calcular los totales), tal vez podamos aprovechar esa misma llamada. Eso sí, yo lo haría con la aproximación "json" y no la "javascript". (en la aproximación "javascript" set_amounts devuelve un codigo javascript que se pega en la página y actualiza las partes tal y cual del html, en la apromación "json" se devuelve un json de datos,  y el javascript de la pagina lo maneja con un callback).

**Comment by ecoslado** [comment]
I've finally chosen the AJAX call with a callback that put the total in its place. I've installed the gon gem and it's easy to put, but, since I didn't use it, I'm going to uninstall it.

If someone thinks this can be useful. Just install the gem and create the Gon object in application.html.haml

```haml
   %body
     = Gon::Base.render_data
     = render partial: 'shared/navbar'
```

And you'll have it available a global gon object in controllers and coffee files. I did a concept test and worked.

**Comment by peillis** [comment]
so unless someone sees an utility for this I'm gonna close it
